name: Renovate
on:
  workflow_dispatch:
    inputs:
      log-level:
        description: "Set the Renovate log level (default: info)"
        required: false
        default: info
        type: choice
        options:
          - info
          - debug
  schedule:
    - cron: '3 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Actions Token
        id: token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v5

      - name: Validate Renovate config
        run: |
          docker run --rm -v "$PWD:/repo" -w /repo \
            ghcr.io/renovatebot/renovate:41 \
            renovate-config-validator renovate-shared-config.json

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.10
        env:
          RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' && 'full' }}
          LOG_LEVEL: ${{ github.event.inputs.log-level || 'info' }}
        with:
          configurationFile: renovate-config.js
          token: '${{ steps.token.outputs.token }}'
